import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthLayout from "./_components/layouts/authLayout";
import MainLayout from "./_components/layouts/mainLayout";
import Session from "./_lib/classes/Session";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await Session.get();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {session ? (
          <MainLayout>{children}</MainLayout>
        ) : (
          <AuthLayout>{children}</AuthLayout>
        )}
      </body>
    </html>
  );
}
